### PR TITLE
board - buttons and background positions fix

### PR DESCRIPTION
**Pull request by DevoAbhi**
## Unallignment and styles of the save and exit button in board component's dashboard.

# Issue number - 184

## Types of changes - UI changes.

_Put an `x` in the boxes that apply_

- [ x ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ x ] My changes generate no new warnings
- [ x ] My changes does not break the current system and it passes all the current test cases.

## Screenshots
 cavasboard_buttons_alligned

## Other information

Please mention if any other changes need to be done.

### CODE REVIEW

**Comment by matheusmosca** [comment]
Hi @DevoAbhi , your PR has solved the issue #184  on my computer. I think @goliakshay357 can merge it.

**Comment by goliakshay357** [comment]
Awesome! Looks good to me! 
Thanks for the contribution :)

**Comment by goliakshay357** [comment]
@all-contributors please add @DevoAbhi  for code.

**Comment by DevoAbhi** [comment]
Thanks @matheusmosca and @goliakshay357 for merging my pull request.

**Pull request merged**
