### PR TITLE
Fix mobile issue

### PR DESCRIPTION
**Pull request by rebelchris**
## Issue that this pull request solves

 Closes: #74 

## Proposed changes

Changed the footer to be center-aligned on Mobile.
Added an alt text for the logo.
Wrapped the logo in a P tag for space on mobile.

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ x ] My changes generate no new warnings
- [ x ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Screenshot 2020-10-01 at 17 05 11

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by goliakshay357** [comment]
@rebelchris , left align would be a better option than center maybe. Apart from that everything is cool enough. 
Thanks!

**Comment by rebelchris** [comment]
@goliakshay357 Removed the text-center and made it left aligned
Screenshot 2020-10-01 at 18 55 20

**Comment by goliakshay357** [comment]
Changed few CSS. looks good to me!
Thank you @rebelchris for this contribution :)

**Comment by goliakshay357** [comment]
@all-contributors please add @rebelchris for Code

**Pull request merged**
