### PR TITLE
Adding Image Slider

### PR DESCRIPTION
**Pull request by Vishal-raj-1**
## Issue that this pull request solves

 Closes: #255

### CODE REVIEW

**Review by kingavatar — CHANGES_REQUESTED** [review]
Provide a GIF or screenshot of the UI changes implemented in PR Description and please make sure to follow default PR description [template](https://github.com/Canvasbird/canvasboard/blob/master/.github/PULL_REQUEST_TEMPLATE.md).

**Comment by Vishal-raj-1** [comment]
Sure !!

> Provide a GIF or screenshot of the UI changes implemented in PR Description and please make sure to follow default PR description [template](https://github.com/Canvasbird/canvasboard/blob/master/.github/PULL_REQUEST_TEMPLATE.md).

Sure !!

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
@Vishal-raj-1 Can you please remove the redundant `home-component.js` file and put all the logic in `home-component.ts` file? Also I don't see the feature working. Can you please check it once on your end and fix it.

**Comment by Vishal-raj-1** [comment]
> @Vishal-raj-1 Can you please remove the redundant `home-component.js` file and put all the logic in `home-component.ts` file? Also I don't see the feature working. Can you please check it once on your end and fix it.

I don't know Typescript Let me done using javascript. then i will convert it to typescript with the use of some references. It may took one or two day to me  I am currently learn React, I have some issues while doing set up for this repository. Let me solve those first then I will solve this issues as well.

**Comment by Kajol-Kumari** [comment]
Hey @Vishal-raj-1 if you have any issue in setting up this repo, feel free to drop the issue in our `general` channel of slack, we would be happy to help you :)

**Comment by Vishal-raj-1** [comment]
> Hey @Vishal-raj-1 if you have any issue in setting up this repo, feel free to drop the issue in our `general` channel of slack, we would be happy to help you :)

Thanks @Kajol-Kumari Mam, It's done Now.

**Comment by Kajol-Kumari** [comment]
Hey @Vishal-raj-1 can you please let us know if you would be able to implement this feature in typescript (Angular 8) or not as it's already a week since we got any update on this PR

**Comment by Vishal-raj-1** [comment]
> Hey @Vishal-raj-1 can you please let us know if you would be able to implement this feature in typescript (Angular 8) or not as it's already a week since we got any update on this PR

Sorry I am learning Javascript and. React.JS. I can't learn typescript or angular without implementation of JS and react. So I am going to close this PR !! 

Sorry for the inconveniences !! I Like your project very much but somehow my stack is not matching( I can learn typescript and angular as well but I think I will learn them later when I will comfortable in JS and react)

**Comment by Kajol-Kumari** [comment]
Thanks for letting us know this @Vishal-raj-1

**Pull request closed without merging**
