### PR TITLE
Add Password Strength Classifier

### PR DESCRIPTION
**Pull request by DevoAbhi**
## Issue that this pull request solves - There is no password strength classifier to prevent the user with a weak password from signup.

 Closes: # (issue number)

## Proposed changes - 
Added a password strength classifier to prevent the user with a weak password from signup.

### Brief description of what is fixed or changed -  
To add a password strength classifier on the signup page. When they try to sign in with a weak password, they are denied to perform the action. Also, the user can see their password strength as a strength meter moves while they enter the password. They can also toggle the visibility of the password. All the necessary checks are mentioned as a tooltip in the password input box.

## Types of changes - 
New feature

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ x ] My changes generate no new warnings
- [ x ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

canva-pass-final

## Other information

Please mention if any changes are required in the PR.

### CODE REVIEW

**Review by Kajol-Kumari — APPROVED** [review]
Feature working fine for large screens and looks good to go :+1:

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
@DevoAbhi I just now found that it's not appearing appropriately on small screens. Please fix this.
Screenshot from 2020-12-28 22-02-05

**Comment by DevoAbhi** [comment]
> @DevoAbhi I just now found that it's not appearing appropriately on small screens. Please fix this.
> Screenshot from 2020-12-28 22-02-05

I have now added a check that if the screen width is lesser than 600 then the tooltip will appear on the bottom and never overlap on the password box. 
Please confirm if the changes are acceptable.

**Review by Kajol-Kumari — APPROVED** [review]
Good to go :+1:

**Comment by DevoAbhi** [comment]
Thank you for merging my PR @Kajol-Kumari . Would love to contribute more!

**Comment by GaganAgarwal77** [comment]
@Kajol-Kumari  Closing this pull request has undone the implementations of #291 , which added ellipses to long folder names, This has happened because an older version of styles.scss was probably used to add implementation for password strength.

**Pull request merged**
