### PR TITLE
Changed Beta font and font-size

### PR DESCRIPTION
**Pull request by Harshita-Kanal**
## Issue that this pull request solves

 Closes: #335 

## Proposed changes
Changed the font-family and font of beta

### Brief description of what is fixed or changed
The font has been changed

## Types of changes

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface
icon
## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
@Harshita-Kanal please revert the changes of the file `angular.json` as we don't need this

**Comment by Harshita-Kanal** [comment]
Reverted the change in `angular.json`

**Comment by goliakshay357** [comment]
LGTM :+1:

**Comment by Harshita-Kanal** [comment]
> LGTM 👍

Thanks, I am from SwoC

**Pull request merged**
