### PR TITLE
Adds undo-redo feature to cb-whiteboard

### PR DESCRIPTION
**Pull request by GaganAgarwal77**
## Issue that this pull request solves

 Closes: #260 

## Proposed changes
Undo Redo feature
### Brief description of what is fixed or changed
Added Undo Redo Feature to cb-whiteboard.ts using another class StateManager that keeps a stack of states, I have also added buttons for the same and a document listener for ctrl + z (undo) and ctrl + y (redo)
## Types of changes
Added Buttons
Added New Class within cb-whiteboard.ts
Made some changes in code.
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Review by kingavatar — CHANGES_REQUESTED** [review]
Looks Good. Just can you solve the merge conflict and push again. Just pull changes from upstream repo before pushing from next time.

**Review by Kajol-Kumari — COMMENTED** [review]
@GaganAgarwal77  Functionality is working fine. I would request just one enhancement in it i.e disable the `redo` button once you get to the present working status and similarly disable the `undo` button once you reach the extreme beginning.

**Comment by GaganAgarwal77** [comment]
@Kajol-Kumari I have made necessary changes, kindly review them.

**Review by Kajol-Kumari — APPROVED** [review]
Thanks for incorporating the requested changes @GaganAgarwal77 
LGTM :+1:

**Pull request merged**
