### PR TITLE
Replaced logout button with dropdown 

### PR DESCRIPTION
**Pull request by Rizwan-S**
## Issue that this pull request solves

 Closes: #290 

### Brief description of what is fixed or changed
Replaces logout button with dropdown.

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots
Changed

## Other information
Hover over the dropdown button to view the dropdown.

### CODE REVIEW

**Review by Kajol-Kumari — APPROVED** [review]
LGTM :+1: 

@goliakshay357 just confirm once if this is exactly what you were expecting it to be as I am a bit not sure.

**Comment by goliakshay357** [comment]
Hello @Rizwan-S , 
Would be great if it is like the following pictures attached. 

For Desktop: 
image

For Mobiles:
image

Dropdown should be enabled only for mobile. 
Source: https://getbootstrap.com/docs/4.0/components/navbar/

**Comment by Rizwan-S** [comment]
Hey @goliakshay357!
Can you let me know if this is what you are expecting? Or if any more changes are required?

For Desktop:
test1

For Mobiles:
test2

This is just a rough sketch. I still need to add some css to make it look better before making a pr.

**Comment by goliakshay357** [comment]
@Rizwan-S , yes!

**Comment by Rizwan-S** [comment]
Hey!
I have made the changes.
This is how it looks like.

For Desktop:
test1

For Mobile:
test2

**Comment by DevoAbhi** [comment]
Have you pulled the changes from the upstream master. The .deepsource.toml file is now added to the upstream master repo.

**Pull request closed without merging**
