### PR TITLE
Dashboard welcome message enhancement 

### PR DESCRIPTION
**Pull request by ShivangiRai1310**
## Issue that this pull request solves

 Closes: #374 

### Brief description of what is fixed or changed
 1. The welcome message is center aligned.
 2. Font style and background color changed.
 3. Close replaces the cross(x) button on hover.

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [x] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface
Screenshot (642)

Here are some other suggestions for background color :

1)
Screenshot (637)

2)
Screenshot (640)

3)
Screenshot (639)

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by goliakshay357** [comment]
Hey @ShivangiRai1310,

The background is really amazing! 
Couple of suggestions:
1) Can we choose the default font?
2) Improvement in terms of padding and margins. 
3) Adding more details to make it look precise. 

A best approach would be is first trying out the design in UI/UX tools like figma or XD, then finalizing the flow. Please Feel free to message me or any mentor in the slack channel for further communications and help.

Thanks.

**Comment by goliakshay357** [comment]
Slack Invite: https://join.slack.com/t/canvasbird-community/shared_invite/zt-lonbgryr-fhsZ5OWGtqDeEbP28GFn0g

**Comment by ShivangiRai1310** [comment]
Hi @goliakshay357 
Please have a look, would be great if the PR could be merged by tonight as DWOC ends today. Apart from that would be glad to work on any other changes required later.
Have done changes in font, text alignment,  added date, added rounder border.

Screenshot (665)

**Comment by goliakshay357** [comment]
Hey @ShivangiRai1310,
This is amazing :tada: 
Thanks for the enhancement!

**Comment by ShivangiRai1310** [comment]
@goliakshay357 
Thanks a lot, would be happy to contribute further.
And could you please add DWOC, SWOC, level labels as well in the merged PR.
Thank you.

**Comment by goliakshay357** [comment]
Please feel free to checkout issues page or you could open new issues. 
Make sure you join our [slack](https://canvasbird-slack.netlify.app/) channel for updates and discussions.

Thanks

**Pull request merged**
