### PR TITLE
Mobile css home page issue fixed

### PR DESCRIPTION
**Pull request by IzacVrushabh**
## Issue that this pull request solves

 Closes: # (97)

## Proposed changes

Brief description of what is fixed or changed
Added default css in app.component.scss ( which is always mandatory )
In home component , added some standard media queries to decrease the margin gap in class links
also fixed the position of class header to the middle.

## Types of changes

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas(no need to add comments in css , i guess)
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

Screenshot (7)

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by IzacVrushabh** [comment]
@goliakshay357  please review it .

**Comment by goliakshay357** [comment]
image

@IzacVrushabh , Is it possible to reduce the **highlighted** font sizes only for the mobile resolution. Do checkout out for iPad resolution also and make changes accordingly.

Thanks

**Comment by goliakshay357** [comment]
You could maybe use @media to solve this issue

**Comment by IzacVrushabh** [comment]
> You could maybe use @media (Standard CSS Command) in SCSS to solve this issue

ok ..yeah i will do it

**Pull request closed without merging**
