### PR TITLE
navigation link to dashboard

### PR DESCRIPTION
**Pull request by okutewonah**
## Issue that this pull request solves

 Closes: #378 

### Brief description of what is fixed or changed
- Added navigation link to redirect to dashboard

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [x ] My changes does not break the current system and it passes all the current test cases.

## Screenshots
navbar

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by goliakshay357** [comment]
Hey @okutewonah,
Thanks for enhancement.

Couple of suggestions,
Can we even have the same dashboard button in the jumbo-tron right below Description instead of having it in the navbar?

Screenshot:
image

Location: /folder/{id}
Thanks.

**Comment by okutewonah** [comment]
Hi @goliakshay357 
I will adjust that in a minute. Thank you for the opportunity.

**Comment by goliakshay357** [comment]
LGTM :+1: 
Thanks for the enhancement. 
Please feel free to checkout other issues and open an issue if anything needs to have an improvement.

**Comment by goliakshay357** [comment]
Is this issue DWOC or SWOC related?

**Comment by okutewonah** [comment]
I believe it had both labels. `SWOC` `DWOC` or maybe I don't understand the question.

**Pull request merged**
