### PR TITLE
Fixed searching renamed folder bug

### PR DESCRIPTION
**Pull request by Dhamodhar-DDR**
## Issue that this pull request solves

 Closes: #303

## Proposed changes
Update the renamed folder name in the data variable that we are using for filtering. 

### Brief description of what is fixed or changed
When the user renames a folder, the folder now appears when it is searched.
Also, corrected few incorrect div ids in the dashboard component.

## Types of changes
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots
https://user-images.githubusercontent.com/56181018/104091617-838b7100-52a4-11eb-97ca-e6e7d33aaa75.mp4

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Review by Kajol-Kumari — APPROVED** [review]
LGTM :+1:

**Comment by Kajol-Kumari** [comment]
@Dhamodhar-DDR can you please let us know, under which program you hace made this PR?

**Comment by Dhamodhar-DDR** [comment]
> @Dhamodhar-DDR can you please let us know, under which program you hace made this PR?

I did not understand.

**Comment by goliakshay357** [comment]
@Dhamodhar-DDR, 
Did you work on this issue via any programs like SWOC, DWOC so we can assign relevant points to you. 

Thanks

**Comment by Dhamodhar-DDR** [comment]
> @Dhamodhar-DDR,
> Did you work on this issue via any programs like SWOC, DWOC so we can assign relevant points to you.
> 
> Thanks

Oh! No, I am not working under any program.

**Pull request merged**
